{% set version = "18.20.0" %}

package:
  name: python-kubernetes
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/k/kubernetes/kubernetes-{{ version }}.tar.gz
  sha256: 0c72d00e7883375bd39ae99758425f5e6cb86388417cf7cc84305c211b2192cf

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: True # [py<36]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=21.0.0
  run:
    - python
    - certifi >=14.05.14
    - google-auth >=1.0.1
    - python-dateutil >=2.5.3
    - pyyaml >=5.4.1
    - requests
    - requests-oauthlib
    - six >=1.9.0
    - urllib3 >=1.24.2
    - websocket-client >=0.32.0,!=0.40.0,!=0.41.*,!=0.42.*

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - kubernetes
    - kubernetes.client
    - kubernetes.client.api
    - kubernetes.client.apis
    - kubernetes.client.models
    - kubernetes.config
    - kubernetes.watch
    - kubernetes.utils

about:
  home: https://github.com/kubernetes-client/python
  license: Apache-2.0
  summary: The official Kubernetes python client.
  description: Python client for kubernetes http://kubernetes.io/
  license_family: APACHE
  license_file: LICENSE
  license_url: https://www.apache.org/licenses/LICENSE-2.0
  dev_url: https://github.com/kubernetes-client/python
  doc_url: https://github.com/kubernetes-client/python/blob/master/README.md
  doc_source_url: https://github.com/kubernetes-client/python/tree/master/doc

extra:
  recipe-maintainers:
    - johanneskoester
    - ocefpaf
