{% set name = "kubernetes" %}
{% set version = "36.0.1" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3eadd6ae1be3b742ae63bd382b139c9fd5171afb6e00771dcefaae2d49001992

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - certifi >=14.05.14
    - six >=1.9.0
    - python-dateutil >=2.5.3
    - setuptools >=21.0.0
    - pyyaml >=6.0.3
    - websocket-client >=0.32.0,!=0.40.0,!=0.41.*,!=0.42.*
    - requests
    - requests-oauthlib
    - urllib3 >=1.24.2,!=2.6.0
    - durationpy >=0.7
  run_constrained:
    - google-auth >=1.0.1

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - kubernetes
    - kubernetes.client
    - kubernetes.client.apis
    - kubernetes.client.models
    - kubernetes.config
    - kubernetes.watch

about:
  home: https://github.com/kubernetes-client/python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: The official Kubernetes python client.
  description: |
    The official Kubernetes python client. This is a client library for
    Kubernetes, an open-source container-orchestration system for automating
    computer application deployment, scaling, and management.
  dev_url: https://github.com/kubernetes-client/python
  doc_url: https://github.com/kubernetes-client/python/blob/master/README.md

extra:
  recipe-maintainers:
    - johanneskoester
    - ocefpaf
