travis:
  secure:
    BINSTAR_TOKEN: Y7X8g6vD0OX8SEmNmPeIGtOBaZ+kFQ47/TVZB5+r23oYVofhE5bbedLihewk2OmJmBIdtIRzWmbd05svM4C5IRrMvYW2GTkGQzpn5ukTjbzLdgc4Tcm9bk/k2iBwFMihpiqFC+xEASqtBoeusxt8zCUcE8kmtBlsYOsXxDUFDxYhCo7zimQMJG25D/FMNabJHt/CgX5r2TtMwRRU77QN8NRwtnMS3OZ2pEzS4C8oM87o4jFyWFB1diWXL6w2MGlsQ7ELbYZfe1RgPsyqMDqf4nLQ9fyZ/V49WxT9SOffu/tBABojUBDnDaiTZv7qPjnvbuccaWYwUSTQY26mMacg9kV1aUMFVMqJPvc5acz+L8TV2x6uchbRdAWtFCnMMLdyKofm7MeAcaSsZRxOch/1APhOl2PuzOt5VyAzqT4k22GDCzhuyTvBXtcI1tBPm2t6+x2zjJ73p1ge9OoM21J0hExCZ2UASU9q/Q5EIi2Rdywlx+NgiIeYFU9ApTWVXCxXtPY6sKKPrfdiHSKRVyOsswbJ0s5Pi+fu6yxvWsXPHlYvNxShvbdFy5cMM33qxhtUYdSqBfsVXGGHtaXucS74Je5xUuYcj+eV+kAB417Tg3NW4vRxcIyZr5Uy7cBSUGa7Ol5rR7/uhoPDQaFXFnYFxAOqhdbM4acT2fpfISlqD6c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
