travis:
  secure:
    BINSTAR_TOKEN: jcFGQ3cUOxuYZ6yLlqfiGgZ9dyTnxNL4N5Ne2i9CWpS+QwkpejqIOENlNXSclH4EQcwJaSkIcg62jEGHc63az3R+MllmCj7S0uzpr+5G5Et+ISF96Xo1F3iLBmO3zMTsIupPpB4c4xSkD0Q6XXwZZLKhPXYrJ3hNdjo1Gs3zsTM/6cydFgqxxflJakO2NyDQmiORj6wxb5rqh+TChyD7mny+91cBaA/HoYkGiJ+ADykUDyOElueqLqMmuSm/By0Ec3E+zalMHO4cGobuSS8BxQ70VZuv2y71ZJg4EMYH0HYqz3d/7K9EOYagZu82914E2odUBr+IiLHIEh8x7MXqjK68OSbO+RO4LSSbNcLLEYVwHfLs3vUjWr0B/0Bykf709FbIpxhz2wNBnkCk2dB7eeW7pUTqIYkmL81d/a53XbJiNEzZ+j89Ftk9w0LVf7ZtRVXf59RZgOcRxYD3ln6ogiKimUb3xDOitzrLNOun1dVug21cpQCmxbDTEyOzcvaw5ZVZzWUyHn1VIVzQ2hobNOwxPhpY2QPxv2hNruw6X2yT8NHVpKTf3pEMtMTgqg+flpQzxO5LekAN7+ZvvJCOdIdw8h0Mgtc/k403p+9P/i3IzCTUluOYcl89biiWBgaVur6axv6z9u5SZGQPuPfVCVQITroi8MsUQvaNaMuvRI8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
