appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: m9JBVulc7Mg4jFYnz1hLxA6Gv3+MrqbYqJ1T+XgrV8smcbOGcHCMna1Qr3k7/QHhryn3+OBf5DWQb0L81CFaKkMhd0IpJbtE4V51XzOjL8C3qEVPBZo0ovti1oadVDz+lJ5qaBiEvuYD4aFh5s50Gg5MbWlzj22Rs4YUnLokwUGALuu3snFi0z0CHBHGOVlPYrRD5O9WRwvp0nzKKNDssbnG+tn1LxgxIN+XatnpS8Wj1wGVGKPnVushBvcuWuR3hUQYGBK3C5g2WaCMzKCSZyTve+ha6aYbGTi1aiUocbo6jiuRfjql9chE7U4pcnVZCNaIR/MZ6GU/E60hyPG7zz79OPrVgEsYNn8QAH0HDc1pJg1+BPWpD6WfkV4Zk3q03nDq9GS0mV5kGiYaz8G+sQAfZpWnpVPPggVpMqu0sQUQxveXO6jthgIDh4aTSSHDBTSUrDfizU6I0/1wXPZj7NTmkgFQNwvb21DPsJKLd6r3Y5yr+lKif76QsXXitEJvRbJ/pHG2RiAoK7n/nK3AZzzaUK11EJzYQDQK9oKKLtRQSXxnVoMcO5RfkpU/J2uF0SQQ+/YEqvBJK1b35E4UwvEAH03xXGQQbL1DSnsJGB5cxdU+plsjvHl2SJ8JJJV3yBwJkM32fG+5cusZJJ+BNWz85pfZkHau9C5GybnHcgY=}
